/*
*/
var io = require('socket.io-client');
var Erizo=Erizo||{};
Erizo.EventDispatcher=function(b){var a={};b.dispatcher={};b.dispatcher.eventListeners={};a.addEventListener=function(a,e){void 0===b.dispatcher.eventListeners[a]&&(b.dispatcher.eventListeners[a]=[]);b.dispatcher.eventListeners[a].push(e)};a.removeEventListener=function(a,e){var g;g=b.dispatcher.eventListeners[a].indexOf(e);-1!==g&&b.dispatcher.eventListeners[a].splice(g,1)};a.dispatchEvent=function(a){var e;L.Logger.debug("Event: "+a.type);for(e in b.dispatcher.eventListeners[a.type])if(b.dispatcher.eventListeners[a.type].hasOwnProperty(e))b.dispatcher.eventListeners[a.type][e](a)};return a};
Erizo.LicodeEvent=function(b){var a={};a.type=b.type;return a};Erizo.RoomEvent=function(b){var a=Erizo.LicodeEvent(b);a.streams=b.streams;a.message=b.message;return a};Erizo.StreamEvent=function(b){var a=Erizo.LicodeEvent(b);a.stream=b.stream;a.msg=b.msg;a.bandwidth=b.bandwidth;return a};Erizo.PublisherEvent=function(b){return Erizo.LicodeEvent(b)};Erizo=Erizo||{};
Erizo.FcStack=function(b){var a={pc_config:{},peerConnection:{},desc:{},signalCallback:void 0,close:function(){console.log("Close FcStack")},createOffer:function(){console.log("FCSTACK: CreateOffer")},addStream:function(a){console.log("FCSTACK: addStream",a)},processSignalingMessage:function(b){console.log("FCSTACK: processSignaling",b);void 0!==a.signalCallback&&a.signalCallback(b)},sendSignalingMessage:function(a){console.log("FCSTACK: Sending signaling Message",a);b.callback(a)},setSignalingCallback:function(b){console.log("FCSTACK: Setting signalling callback");
a.signalCallback=b}};return a};Erizo=Erizo||{};
Erizo.ChromeStableStack=function(b){var a={pc_config:{iceServers:[]},con:{optional:[{DtlsSrtpKeyAgreement:!0}]}};void 0!==b.iceServers&&(a.pc_config.iceServers=b.iceServers);void 0===b.audio&&(b.audio=!0);void 0===b.video&&(b.video=!0);a.mediaConstraints={mandatory:{OfferToReceiveVideo:b.video,OfferToReceiveAudio:b.audio}};var d=function(a){L.Logger.error("Error in Stack ",a)};a.peerConnection=new webkitRTCPeerConnection(a.pc_config,a.con);var e=function(a){if(b.video&&b.maxVideoBW){var a=a.replace(/b=AS:.*\r\n/g,
""),f=a.match(/m=video.*\r\n/);f==null&&(f=a.match(/m=video.*\n/));if(f&&f.length>0)var g=f[0]+"b=AS:"+b.maxVideoBW+"\r\n",a=a.replace(f[0],g)}if(b.audio&&b.maxAudioBW){f=a.match(/m=audio.*\r\n/);f==null&&(f=a.match(/m=audio.*\n/));if(f&&f.length>0){g=f[0]+"b=AS:"+b.maxAudioBW+"\r\n";a=a.replace(f[0],g)}}return a};a.close=function(){a.state="closed";a.peerConnection.close()};b.localCandidates=[];a.peerConnection.onicecandidate=function(a){var f={};if(a.candidate){if(!a.candidate.candidate.match(/a=/))a.candidate.candidate=
"a="+a.candidate.candidate;f={sdpMLineIndex:a.candidate.sdpMLineIndex,sdpMid:a.candidate.sdpMid,candidate:a.candidate.candidate}}else{L.Logger.info("Gathered all candidates. Sending END candidate");f={sdpMLineIndex:-1,sdpMid:"end",candidate:"end"}}if(b.remoteDescriptionSet)b.callback({type:"candidate",candidate:f});else{b.localCandidates.push(f);L.Logger.info("Storing candidate: ",b.localCandidates.length,f)}};a.peerConnection.onaddstream=function(b){if(a.onaddstream)a.onaddstream(b)};a.peerConnection.onremovestream=
function(b){if(a.onremovestream)a.onremovestream(b)};a.peerConnection.oniceconnectionstatechange=function(b){if(a.oniceconnectionstatechange)a.oniceconnectionstatechange(b.target.iceConnectionState)};var g,h,i=function(a){a.sdp=e(a.sdp);a.sdp=a.sdp.replace(/a=ice-options:google-ice\r\n/g,"");b.callback({type:a.type,sdp:a.sdp});g=a},j=function(c){c.sdp=e(c.sdp);b.callback({type:c.type,sdp:c.sdp});g=c;a.peerConnection.setLocalDescription(c)};a.updateSpec=function(c,f){if(c.maxVideoBW||c.maxAudioBW){if(c.maxVideoBW){L.Logger.debug("Maxvideo Requested",
c.maxVideoBW,"limit",b.limitMaxVideoBW);if(c.maxVideoBW>b.limitMaxVideoBW)c.maxVideoBW=b.limitMaxVideoBW;b.maxVideoBW=c.maxVideoBW;L.Logger.debug("Result",b.maxVideoBW)}if(c.maxAudioBW){if(c.maxAudioBW>b.limitMaxAudioBW)c.maxAudioBW=b.limitMaxAudioBW;b.maxAudioBW=c.maxAudioBW}g.sdp=e(g.sdp);if(c.Sdp||c.maxAudioBW){L.Logger.debug("Updating with SDP renegotiation",b.maxVideoBW);a.peerConnection.setLocalDescription(g,function(){h.sdp=e(h.sdp);a.peerConnection.setRemoteDescription(new RTCSessionDescription(h),
function(){b.remoteDescriptionSet=true;b.callback({type:"updatestream",sdp:g.sdp})})},function(a){L.Logger.error("Error updating configuration",a);f("error")})}else{L.Logger.debug("Updating without SDP renegotiation, newVideoBW:",b.maxVideoBW,"newAudioBW:",b.maxAudioBW);b.callback({type:"updatestream",sdp:g.sdp})}}if(c.minVideoBW||c.slideShowMode!==void 0){L.Logger.debug("MinVideo Changed to ",c.minVideoBW);L.Logger.debug("SlideShowMode Changed to ",c.slideShowMode);b.callback({type:"updatestream",
config:c})}};a.createOffer=function(b){b===true?a.peerConnection.createOffer(i,d,a.mediaConstraints):a.peerConnection.createOffer(i,d)};a.addStream=function(b){a.peerConnection.addStream(b)};b.remoteCandidates=[];b.remoteDescriptionSet=!1;a.processSignalingMessage=function(c){if(c.type==="offer"){c.sdp=e(c.sdp);a.peerConnection.setRemoteDescription(new RTCSessionDescription(c),function(){a.peerConnection.createAnswer(j,function(a){L.Logger.error("Error: ",a)},a.mediaConstraints);b.remoteDescriptionSet=
true},function(a){L.Logger.error("Error setting Remote Description",a)})}else if(c.type==="answer"){L.Logger.info("Set remote and local description");L.Logger.debug("Remote Description",c.sdp);L.Logger.debug("Local Description",g.sdp);c.sdp=e(c.sdp);h=c;a.peerConnection.setLocalDescription(g,function(){a.peerConnection.setRemoteDescription(new RTCSessionDescription(c),function(){b.remoteDescriptionSet=true;for(L.Logger.info("Candidates to be added: ",b.remoteCandidates.length,b.remoteCandidates);b.remoteCandidates.length>
0;)a.peerConnection.addIceCandidate(b.remoteCandidates.shift());for(L.Logger.info("Local candidates to send:",b.localCandidates.length);b.localCandidates.length>0;)b.callback({type:"candidate",candidate:b.localCandidates.shift()})})})}else if(c.type==="candidate")try{var f;f=typeof c.candidate==="object"?c.candidate:JSON.parse(c.candidate);f.candidate=f.candidate.replace(/a=/g,"");f.sdpMLineIndex=parseInt(f.sdpMLineIndex);var k=new RTCIceCandidate(f);b.remoteDescriptionSet?a.peerConnection.addIceCandidate(k):
b.remoteCandidates.push(k)}catch(d){L.Logger.error("Error parsing candidate",c.candidate)}};return a};Erizo=Erizo||{};
Erizo.ChromeCanaryStack=function(b){var a={},d=webkitRTCPeerConnection;a.pc_config={iceServers:[]};a.con={optional:[{DtlsSrtpKeyAgreement:!0}]};void 0!==b.stunServerUrl&&a.pc_config.iceServers.push({url:b.stunServerUrl});(b.turnServer||{}).url&&a.pc_config.iceServers.push({username:b.turnServer.username,credential:b.turnServer.password,url:b.turnServer.url});if(void 0===b.audio||b.nop2p)b.audio=!0;if(void 0===b.video||b.nop2p)b.video=!0;a.mediaConstraints={mandatory:{OfferToReceiveVideo:b.video,OfferToReceiveAudio:b.audio}};
a.roapSessionId=103;a.peerConnection=new d(a.pc_config,a.con);a.peerConnection.onicecandidate=function(g){L.Logger.debug("PeerConnection: ",b.session_id);if(g.candidate)a.iceCandidateCount+=1;else if(L.Logger.debug("State: "+a.peerConnection.iceGatheringState),void 0===a.ices&&(a.ices=0),a.ices+=1,1<=a.ices&&a.moreIceComing)a.moreIceComing=!1,a.markActionNeeded()};var e=function(a){if(b.maxVideoBW){var e=a.match(/m=video.*\r\n/);if(e&&0<e.length)var d=e[0]+"b=AS:"+b.maxVideoBW+"\r\n",a=a.replace(e[0],
d)}if(b.maxAudioBW&&(e=a.match(/m=audio.*\r\n/))&&0<e.length)d=e[0]+"b=AS:"+b.maxAudioBW+"\r\n",a=a.replace(e[0],d);return a};a.processSignalingMessage=function(b){L.Logger.debug("Activity on conn "+a.sessionId);b=JSON.parse(b);a.incomingMessage=b;"new"===a.state?"OFFER"===b.messageType?(b={sdp:b.sdp,type:"offer"},a.peerConnection.setRemoteDescription(new RTCSessionDescription(b)),a.state="offer-received",a.markActionNeeded()):a.error("Illegal message for this state: "+b.messageType+" in state "+
a.state):"offer-sent"===a.state?"ANSWER"===b.messageType?(b={sdp:b.sdp,type:"answer"},L.Logger.debug("Received ANSWER: ",b.sdp),b.sdp=e(b.sdp),a.peerConnection.setRemoteDescription(new RTCSessionDescription(b)),a.sendOK(),a.state="established"):"pr-answer"===b.messageType?(b={sdp:b.sdp,type:"pr-answer"},a.peerConnection.setRemoteDescription(new RTCSessionDescription(b))):"offer"===b.messageType?a.error("Not written yet"):a.error("Illegal message for this state: "+b.messageType+" in state "+a.state):
"established"===a.state&&("OFFER"===b.messageType?(b={sdp:b.sdp,type:"offer"},a.peerConnection.setRemoteDescription(new RTCSessionDescription(b)),a.state="offer-received",a.markActionNeeded()):a.error("Illegal message for this state: "+b.messageType+" in state "+a.state))};a.addStream=function(b){a.peerConnection.addStream(b);a.markActionNeeded()};a.removeStream=function(){a.markActionNeeded()};a.close=function(){a.state="closed";a.peerConnection.close()};a.markActionNeeded=function(){a.actionNeeded=
!0;a.doLater(function(){a.onstablestate()})};a.doLater=function(a){window.setTimeout(a,1)};a.onstablestate=function(){var b;if(a.actionNeeded){if("new"===a.state||"established"===a.state)a.peerConnection.createOffer(function(b){b.sdp=e(b.sdp);L.Logger.debug("Changed",b.sdp);b.sdp!==a.prevOffer?(a.peerConnection.setLocalDescription(b),a.state="preparing-offer",a.markActionNeeded()):L.Logger.debug("Not sending a new offer")},null,a.mediaConstraints);else if("preparing-offer"===a.state){if(a.moreIceComing)return;
a.prevOffer=a.peerConnection.localDescription.sdp;L.Logger.debug("Sending OFFER: "+a.prevOffer);a.sendMessage("OFFER",a.prevOffer);a.state="offer-sent"}else if("offer-received"===a.state)a.peerConnection.createAnswer(function(b){a.peerConnection.setLocalDescription(b);a.state="offer-received-preparing-answer";a.iceStarted?a.markActionNeeded():(L.Logger.debug((new Date).getTime()+": Starting ICE in responder"),a.iceStarted=!0)},null,a.mediaConstraints);else if("offer-received-preparing-answer"===a.state){if(a.moreIceComing)return;
b=a.peerConnection.localDescription.sdp;a.sendMessage("ANSWER",b);a.state="established"}else a.error("Dazed and confused in state "+a.state+", stopping here");a.actionNeeded=!1}};a.sendOK=function(){a.sendMessage("OK")};a.sendMessage=function(b,e){var d={};d.messageType=b;d.sdp=e;"OFFER"===b?(d.offererSessionId=a.sessionId,d.answererSessionId=a.otherSessionId,d.seq=a.sequenceNumber+=1,d.tiebreaker=Math.floor(429496723*Math.random()+1)):(d.offererSessionId=a.incomingMessage.offererSessionId,d.answererSessionId=
a.sessionId,d.seq=a.incomingMessage.seq);a.onsignalingmessage(JSON.stringify(d))};a.error=function(a){throw"Error in RoapOnJsep: "+a;};a.sessionId=a.roapSessionId+=1;a.sequenceNumber=0;a.actionNeeded=!1;a.iceStarted=!1;a.moreIceComing=!0;a.iceCandidateCount=0;a.onsignalingmessage=b.callback;a.peerConnection.onopen=function(){if(a.onopen)a.onopen()};a.peerConnection.onaddstream=function(b){if(a.onaddstream)a.onaddstream(b)};a.peerConnection.onremovestream=function(b){if(a.onremovestream)a.onremovestream(b)};
a.peerConnection.oniceconnectionstatechange=function(b){if(a.oniceconnectionstatechange)a.oniceconnectionstatechange(b.currentTarget.iceConnectionState)};a.onaddstream=null;a.onremovestream=null;a.state="new";a.markActionNeeded();return a};Erizo=Erizo||{};Erizo.sessionId=103;
Erizo.Connection=function(b){var a={};b.session_id=Erizo.sessionId+=1;a.browser=Erizo.getBrowser();if("fake"===a.browser)L.Logger.warning("Publish/subscribe video/audio streams not supported in erizofc yet"),a=Erizo.FcStack(b);else if("mozilla"===a.browser)L.Logger.debug("Firefox Stack"),a=Erizo.FirefoxStack(b);else if("bowser"===a.browser)L.Logger.debug("Bowser Stack"),a=Erizo.BowserStack(b);else if("chrome-stable"===a.browser)L.Logger.debug("Chrome Stable Stack"),a=Erizo.ChromeStableStack(b);else throw L.Logger.error("No stack available for this browser"),
"WebRTC stack not available";a.updateSpec||(a.updateSpec=function(a,b){L.Logger.error("Update Configuration not implemented in this browser");b&&b("unimplemented")});return a};
Erizo.getBrowser=function(){var b="none";"undefined"!==typeof module&&module.exports?b="fake":null!==window.navigator.userAgent.match("Firefox")?b="mozilla":null!==window.navigator.userAgent.match("Bowser")?b="bowser":null!==window.navigator.userAgent.match("Chrome")?26<=window.navigator.appVersion.match(/Chrome\/([\w\W]*?)\./)[1]&&(b="chrome-stable"):null!==window.navigator.userAgent.match("Safari")?b="bowser":null!==window.navigator.userAgent.match("AppleWebKit")&&(b="bowser");return b};
Erizo.GetUserMedia=function(b,a,d){navigator.getMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia;if(b.screen)switch(L.Logger.debug("Screen access requested"),Erizo.getBrowser()){case "mozilla":L.Logger.debug("Screen sharing in Firefox");var e={};void 0!=b.video.mandatory?(e.video=b.video,e.video.mediaSource="window"):e={audio:b.audio,video:{mediaSource:"window"}};navigator.getMedia(e,a,d);break;case "chrome-stable":L.Logger.debug("Screen sharing in Chrome");
e="okeephmleflklcdebijnponpabbmmgeo";b.extensionId&&(L.Logger.debug("extensionId supplied, using "+b.extensionId),e=b.extensionId);L.Logger.debug("Screen access on chrome stable, looking for extension");try{chrome.runtime.sendMessage(e,{getStream:!0},function(e){var g={};if(e==void 0){L.Logger.error("Access to screen denied");d({code:"Access to screen denied"})}else{e=e.streamId;if(b.video.mandatory!=void 0){g.video=b.video;g.video.mandatory.chromeMediaSource="desktop";g.video.mandatory.chromeMediaSourceId=
e}else g={video:{mandatory:{chromeMediaSource:"desktop",chromeMediaSourceId:e}}};navigator.getMedia(g,a,d)}})}catch(g){L.Logger.debug("Screensharing plugin is not accessible ");d({code:"no_plugin_present"});break}break;default:L.Logger.error("This browser does not support ScreenSharing")}else"undefined"!==typeof module&&module.exports?L.Logger.error("Video/audio streams not supported in erizofc yet"):navigator.getMedia(b,a,d)};Erizo=Erizo||{};
Erizo.Stream=function(b){var a=Erizo.EventDispatcher(b),d;a.stream=b.stream;a.url=b.url;a.recording=b.recording;a.room=void 0;a.showing=!1;a.local=!1;a.video=b.video;a.audio=b.audio;a.screen=b.screen;a.videoSize=b.videoSize;a.extensionId=b.extensionId;if(void 0!==a.videoSize&&(!(a.videoSize instanceof Array)||4!=a.videoSize.length))throw Error("Invalid Video Size");if(void 0===b.local||!0===b.local)a.local=!0;a.getID=function(){return a.local&&!b.streamID?"local":b.streamID};a.getAttributes=function(){return b.attributes};
a.setAttributes=function(){L.Logger.error("Failed to set attributes data. This Stream object has not been published.")};a.updateLocalAttributes=function(a){b.attributes=a};a.hasAudio=function(){return b.audio};a.hasVideo=function(){return b.video};a.hasData=function(){return b.data};a.hasScreen=function(){return b.screen};a.sendData=function(){L.Logger.error("Failed to send data. This Stream object has not that channel enabled.")};a.init=function(){try{if((b.audio||b.video||b.screen)&&void 0===b.url){L.Logger.info("Requested access to local media");
var e=b.video;(!0==e||!0==b.screen)&&void 0!==a.videoSize?e={mandatory:{minWidth:a.videoSize[0],minHeight:a.videoSize[1],maxWidth:a.videoSize[2],maxHeight:a.videoSize[3]}}:!0==b.screen&&void 0===e&&(e=!0);var d={video:e,audio:b.audio,fake:b.fake,screen:b.screen,extensionId:a.extensionId};L.Logger.debug(d);Erizo.GetUserMedia(d,function(b){L.Logger.info("User has granted access to local media.");a.stream=b;b=Erizo.StreamEvent({type:"access-accepted"});a.dispatchEvent(b)},function(b){L.Logger.error("Failed to get access to local media. Error code was "+
b.code+".");b=Erizo.StreamEvent({type:"access-denied",msg:b});a.dispatchEvent(b)})}else{var h=Erizo.StreamEvent({type:"access-accepted"});a.dispatchEvent(h)}}catch(i){L.Logger.error("Failed to get access to local media. Error was "+i+"."),h=Erizo.StreamEvent({type:"access-denied",msg:i}),a.dispatchEvent(h)}};a.close=function(){a.local&&(void 0!==a.room&&a.room.unpublish(a),a.hide(),void 0!==a.stream&&a.stream.getTracks().forEach(function(a){a.stop()}),a.stream=void 0)};a.play=function(b,d){d=d||{};
a.elementID=b;if(a.hasVideo()||this.hasScreen()){if(void 0!==b){var h=new Erizo.VideoPlayer({id:a.getID(),stream:a,elementID:b,options:d});a.player=h;a.showing=!0}}else a.hasAudio&&(h=new Erizo.AudioPlayer({id:a.getID(),stream:a,elementID:b,options:d}),a.player=h,a.showing=!0)};a.stop=function(){a.showing&&void 0!==a.player&&(a.player.destroy(),a.showing=!1)};a.show=a.play;a.hide=a.stop;d=function(){if(void 0!==a.player&&void 0!==a.stream){var b=a.player.video,d=document.defaultView.getComputedStyle(b),
h=parseInt(d.getPropertyValue("width"),10),i=parseInt(d.getPropertyValue("height"),10),j=parseInt(d.getPropertyValue("left"),10),d=parseInt(d.getPropertyValue("top"),10),c=document.getElementById(a.elementID),f=document.defaultView.getComputedStyle(c),c=parseInt(f.getPropertyValue("width"),10),f=parseInt(f.getPropertyValue("height"),10),k=document.createElement("canvas");k.id="testing";k.width=c;k.height=f;k.setAttribute("style","display: none");k.getContext("2d").drawImage(b,j,d,h,i);return k}return null};
a.getVideoFrameURL=function(a){var b=d();return null!==b?a?b.toDataURL(a):b.toDataURL():null};a.getVideoFrame=function(){var a=d();return null!==a?a.getContext("2d").getImageData(0,0,a.width,a.height):null};a.checkOptions=function(b,d){if(!0===d){if(b.video||b.audio||b.screen)L.Logger.warning("Cannot update type of subscription"),b.video=void 0,b.audio=void 0,b.screen=void 0}else if(!1===a.local&&(!0===b.video&&!1===a.hasVideo()&&(L.Logger.warning("Trying to subscribe to video when there is no video, won't subscribe to video"),
b.video=!1),!0===b.audio&&!1===a.hasAudio()))L.Logger.warning("Trying to subscribe to audio when there is no audio, won't subscribe to audio"),b.audio=!1;!1===a.local&&!a.hasVideo()&&!0===b.slideShowMode&&(L.Logger.warning("Cannot enable slideShowMode if it is not a video subscription, please check your parameters"),b.slideShowMode=!1)};a.updateConfiguration=function(b,d){if(void 0!==b)if(a.pc)if(a.checkOptions(b,!0),a.local)if(a.room.p2p)for(var h in a.pc)a.pc[h].updateSpec(b,d);else a.pc.updateSpec(b,
d);else a.pc.updateSpec(b,d);else return"This stream has no peerConnection attached, ignoring"};return a};Erizo=Erizo||{};
Erizo.Room=function(b){var a=Erizo.EventDispatcher(b),d,e,g,h,i,j;a.remoteStreams={};a.localStreams={};a.roomID="";a.socket={};a.state=0;a.p2p=!1;a.addEventListener("room-disconnected",function(){var b,f;a.state=0;for(b in a.remoteStreams)a.remoteStreams.hasOwnProperty(b)&&(f=a.remoteStreams[b],j(f),delete a.remoteStreams[b],f&&!f.failed&&(f=Erizo.StreamEvent({type:"stream-removed",stream:f}),a.dispatchEvent(f)));a.remoteStreams={};for(b in a.localStreams)if(a.localStreams.hasOwnProperty(b)){f=a.localStreams[b];
if(a.p2p)for(var d in f.pc)f.pc[d].close();else f.pc.close();delete a.localStreams[b]}try{a.socket.disconnect()}catch(e){L.Logger.debug("Socket already disconnected")}a.socket=void 0});j=function(a){void 0!==a.stream&&(a.hide(),a.pc&&a.pc.close(),a.local&&a.stream.stop(),delete a.stream)};h=function(a,b){a.local?e("sendDataStream",{id:a.getID(),msg:b}):L.Logger.error("You can not send data through a remote stream")};i=function(a,b){a.local?(a.updateLocalAttributes(b),e("updateStreamAttributes",{id:a.getID(),
attrs:b})):L.Logger.error("You can not update attributes in a remote stream")};d=function(c,f,d){a.socket=io.connect(c.host,{reconnect:!1,secure:c.secure,"force new connection":!0,transports:["websocket"]});a.socket.on("onAddStream",function(b){var c=Erizo.Stream({streamID:b.id,local:!1,audio:b.audio,video:b.video,data:b.data,screen:b.screen,attributes:b.attributes});a.remoteStreams[b.id]=c;b=Erizo.StreamEvent({type:"stream-added",stream:c});a.dispatchEvent(b)});a.socket.on("signaling_message_erizo",
function(b){var c;(c=b.peerId?a.remoteStreams[b.peerId]:a.localStreams[b.streamId])&&!c.failed&&c.pc.processSignalingMessage(b.mess)});a.socket.on("signaling_message_peer",function(b){var c=a.localStreams[b.streamId];c&&!c.failed?c.pc[b.peerSocket].processSignalingMessage(b.msg):(c=a.remoteStreams[b.streamId],c.pc||m(c,b.peerSocket),c.pc.processSignalingMessage(b.msg))});a.socket.on("publish_me",function(b){var c=a.localStreams[b.streamId];void 0===c.pc&&(c.pc={});c.pc[b.peerSocket]=Erizo.Connection({callback:function(a){g("signaling_message",
{streamId:b.streamId,peerSocket:b.peerSocket,msg:a})},audio:c.hasAudio(),video:c.hasVideo(),iceServers:a.iceServers});c.pc[b.peerSocket].oniceconnectionstatechange=function(a){if(a==="failed"){c.pc[b.peerSocket].close();delete c.pc[b.peerSocket]}};c.pc[b.peerSocket].addStream(c.stream);c.pc[b.peerSocket].createOffer()});var m=function(c,f){c.pc=Erizo.Connection({callback:function(a){g("signaling_message",{streamId:c.getID(),peerSocket:f,msg:a})},iceServers:a.iceServers,maxAudioBW:b.maxAudioBW,maxVideoBW:b.maxVideoBW,
limitMaxAudioBW:b.maxAudioBW,limitMaxVideoBW:b.maxVideoBW});c.pc.onaddstream=function(b){L.Logger.info("Stream subscribed");c.stream=b.stream;b=Erizo.StreamEvent({type:"stream-subscribed",stream:c});a.dispatchEvent(b)}};a.socket.on("onBandwidthAlert",function(b){L.Logger.info("Bandwidth Alert on",b.streamID,"message",b.message,"BW:",b.bandwidth);if(b.streamID){var c=a.remoteStreams[b.streamID];c&&!c.failed&&(b=Erizo.StreamEvent({type:"bandwidth-alert",stream:c,msg:b.message,bandwidth:b.bandwidth}),
c.dispatchEvent(b))}});a.socket.on("onDataStream",function(b){var c=a.remoteStreams[b.id],b=Erizo.StreamEvent({type:"stream-data",msg:b.msg,stream:c});c.dispatchEvent(b)});a.socket.on("onUpdateAttributeStream",function(b){var c=a.remoteStreams[b.id],f=Erizo.StreamEvent({type:"stream-attributes-update",attrs:b.attrs,stream:c});c.updateLocalAttributes(b.attrs);c.dispatchEvent(f)});a.socket.on("onRemoveStream",function(b){var c=a.localStreams[b.id];c&&!c.failed?(c.failed=!0,L.Logger.warning("We received a removeStream from our own stream -- probably erizoJS timed out"),
b=Erizo.StreamEvent({type:"stream-failed",msg:"Publishing local stream failed because of an Erizo Error",stream:c}),a.dispatchEvent(b),a.unpublish(c)):(c=a.remoteStreams[b.id])&&c.failed?L.Logger.debug("Received onRemoveStream for a stream that we already marked as failed ",b.id):c?(delete a.remoteStreams[b.id],j(c),c=Erizo.StreamEvent({type:"stream-removed",stream:c}),a.dispatchEvent(c)):L.Logger.debug("Received a removeStream for",b.id,"and it has not been registered here, ignoring.")});a.socket.on("disconnect",
function(){L.Logger.info("Socket disconnected, lost connection to ErizoController");if(0!==a.state){L.Logger.error("Unexpected disconnection from ErizoController");var b=Erizo.RoomEvent({type:"room-disconnected",message:"unexpected-disconnection"});a.dispatchEvent(b)}});a.socket.on("connection_failed",function(b){if("publish"===b.type){if(L.Logger.error("ICE Connection Failed on publishing stream",b.streamId,a.state),0!==a.state&&b.streamId&&(b=a.localStreams[b.streamId])&&!b.failed){b.failed=!0;
var c=Erizo.StreamEvent({type:"stream-failed",msg:"Publishing local stream failed ICE Checks",stream:b});a.dispatchEvent(c);a.unpublish(b)}}else if(L.Logger.error("ICE Connection Failed on subscribe stream",b.streamId),0!==a.state&&b.streamId&&(b=a.remoteStreams[b.streamId])&&!b.failed)b.failed=!0,c=Erizo.StreamEvent({type:"stream-failed",msg:"Subscriber failed the ICE Checks, cannot reach Licode for media",stream:b}),a.dispatchEvent(c),a.unsubscribe(b)});a.socket.on("error",function(a){L.Logger.error("Cannot connect to erizo Controller");
d&&d("Cannot connect to ErizoController (socket.io error)",a)});e("token",c,f,d)};e=function(b,f,d,e){a.socket.emit(b,f,function(a,b){"success"===a?d&&d(b):"error"===a?e&&e(b):d&&d(a,b)})};g=function(b,f,d,e){0!==a.state?a.socket.emit(b,f,d,function(a,b){e&&e(a,b)}):L.Logger.warning("Trying to send a message over a disconnected Socket")};a.connect=function(){var c=L.Base64.decodeBase64(b.token);0!==a.state&&L.Logger.warning("Room already connected");a.state=1;d(JSON.parse(c),function(c){var d=0,e=
[],g,h,l;g=c.streams||[];a.p2p=c.p2p;h=c.id;a.iceServers=c.iceServers;a.state=2;b.defaultVideoBW=c.defaultVideoBW;b.maxVideoBW=c.maxVideoBW;for(d in g)g.hasOwnProperty(d)&&(l=g[d],c=Erizo.Stream({streamID:l.id,local:!1,audio:l.audio,video:l.video,data:l.data,screen:l.screen,attributes:l.attributes}),e.push(c),a.remoteStreams[l.id]=c);a.roomID=h;L.Logger.info("Connected to room "+a.roomID);d=Erizo.RoomEvent({type:"room-connected",streams:e});a.dispatchEvent(d)},function(b){L.Logger.error("Not Connected! Error: "+
b);b=Erizo.RoomEvent({type:"room-error",message:b});a.dispatchEvent(b)})};a.disconnect=function(){L.Logger.debug("Disconnection requested");var b=Erizo.RoomEvent({type:"room-disconnected",message:"expected-disconnection"});a.dispatchEvent(b)};a.publish=function(c,f,d){f=f||{};f.maxVideoBW=f.maxVideoBW||b.defaultVideoBW;f.maxVideoBW>b.maxVideoBW&&(f.maxVideoBW=b.maxVideoBW);void 0===f.minVideoBW&&(f.minVideoBW=0);f.minVideoBW>b.defaultVideoBW&&(f.minVideoBW=b.defaultVideoBW);if(c&&c.local&&void 0===
a.localStreams[c.getID()])if(c.hasAudio()||c.hasVideo()||c.hasScreen())if(void 0!==c.url||void 0!==c.recording){var e,n;c.url?(e="url",n=c.url):(e="recording",n=c.recording);L.Logger.info("Checking publish options for",c.getID());c.checkOptions(f);g("publish",{state:e,data:c.hasData(),audio:c.hasAudio(),video:c.hasVideo(),attributes:c.getAttributes(),createOffer:f.createOffer},n,function(b,f){if(b!==null){L.Logger.info("Stream published");c.getID=function(){return b};c.sendData=function(a){h(c,a)};
c.setAttributes=function(a){i(c,a)};a.localStreams[b]=c;c.room=a;d&&d(b)}else{L.Logger.error("Error when publishing stream",f);d&&d(void 0,f)}})}else a.p2p?(b.maxAudioBW=f.maxAudioBW,b.maxVideoBW=f.maxVideoBW,g("publish",{state:"p2p",data:c.hasData(),audio:c.hasAudio(),video:c.hasVideo(),screen:c.hasScreen(),attributes:c.getAttributes()},void 0,function(b,f){if(b===null){L.Logger.error("Error when publishing the stream",f);d&&d(void 0,f)}L.Logger.info("Stream published");c.getID=function(){return b};
if(c.hasData())c.sendData=function(a){h(c,a)};c.setAttributes=function(a){i(c,a)};a.localStreams[b]=c;c.room=a})):(L.Logger.info("Publishing to Erizo Normally, is createOffer",f.createOffer),g("publish",{state:"erizo",data:c.hasData(),audio:c.hasAudio(),video:c.hasVideo(),screen:c.hasScreen(),minVideoBW:f.minVideoBW,attributes:c.getAttributes(),createOffer:f.createOffer,scheme:f.scheme},void 0,function(e,m){if(e===null){L.Logger.error("Error when publishing the stream: ",m);d&&d(void 0,m)}else{L.Logger.info("Stream assigned an Id, starting the publish process");
c.getID=function(){return e};if(c.hasData())c.sendData=function(a){h(c,a)};c.setAttributes=function(a){i(c,a)};a.localStreams[e]=c;c.room=a;c.pc=Erizo.Connection({callback:function(a){L.Logger.debug("Sending message",a);g("signaling_message",{streamId:c.getID(),msg:a},void 0,function(){})},iceServers:a.iceServers,maxAudioBW:f.maxAudioBW,maxVideoBW:f.maxVideoBW,limitMaxAudioBW:b.maxAudioBW,limitMaxVideoBW:b.maxVideoBW,audio:c.hasAudio(),video:c.hasVideo()});c.pc.addStream(c.stream);c.pc.oniceconnectionstatechange=
function(b){if(b==="failed"&&a.state!==0&&c&&!c.failed){c.failed=true;L.Logger.warning("Publishing Stream",c.getID(),"has failed after successful ICE checks");b=Erizo.StreamEvent({type:"stream-failed",msg:"Publishing stream failed after connection",stream:c});a.dispatchEvent(b);a.unpublish(c)}};f.createOffer||c.pc.createOffer();d&&d(e)}}));else c.hasData()&&g("publish",{state:"data",data:c.hasData(),audio:!1,video:!1,screen:!1,attributes:c.getAttributes()},void 0,function(b,f){if(b===null){L.Logger.error("Error publishing stream ",
f);d&&d(void 0,f)}else{L.Logger.info("Stream published");c.getID=function(){return b};c.sendData=function(a){h(c,a)};c.setAttributes=function(a){i(c,a)};a.localStreams[b]=c;c.room=a;d&&d(b)}});else L.Logger.error("Trying to publish invalid stream"),d&&d(void 0,"Invalid Stream")};a.startRecording=function(a,b){a?(L.Logger.debug("Start Recording stream: "+a.getID()),e("startRecorder",{to:a.getID()},function(a,c){null===a?(L.Logger.error("Error on start recording",c),b&&b(void 0,c)):(L.Logger.info("Start recording",
a),b&&b(a))})):(L.Logger.error("Trying to start recording on an invalid stream",a),b&&b(void 0,"Invalid Stream"))};a.stopRecording=function(a,b){e("stopRecorder",{id:a},function(d,e){null===d?(L.Logger.error("Error on stop recording",e),b&&b(void 0,e)):(L.Logger.info("Stop recording",a),b&&b(!0))})};a.unpublish=function(b,d){if(b&&b.local){e("unpublish",b.getID(),function(a,b){null===a?(L.Logger.error("Error unpublishing stream",b),d&&d(void 0,b)):(L.Logger.info("Stream unpublished"),d&&d(!0))});
var g=b.room&&b.room.p2p;b.room=void 0;if((b.hasAudio()||b.hasVideo()||b.hasScreen())&&void 0===b.url)if(g)for(var h in b.pc)b.pc[h].close(),b.pc[h]=void 0;else b.pc&&b.pc.close(),b.pc=void 0;delete a.localStreams[b.getID()];b.getID=function(){};b.sendData=function(){};b.setAttributes=function(){}}else L.Logger.error("Cannot unpublish, stream does not exist or is not local"),d&&d(void 0,error)};a.subscribe=function(b,d,e){d=d||{};if(b&&!b.local){if(b.hasVideo()||b.hasAudio()||b.hasScreen())a.p2p?
(g("subscribe",{streamId:b.getID()}),e&&e(!0)):(L.Logger.info("Checking subscribe options for",b.getID()),b.checkOptions(d),g("subscribe",{streamId:b.getID(),audio:d.audio,video:d.video,data:d.data,browser:Erizo.getBrowser(),createOffer:d.createOffer,slideShowMode:d.slideShowMode},void 0,function(h,m){null===h?(L.Logger.error("Error subscribing to stream ",m),e&&e(void 0,m)):(L.Logger.info("Subscriber added"),b.pc=Erizo.Connection({callback:function(a){L.Logger.info("Sending message",a);g("signaling_message",
{streamId:b.getID(),msg:a,browser:b.pc.browser},void 0,function(){})},nop2p:!0,audio:d.audio,video:d.video,iceServers:a.iceServers}),b.pc.onaddstream=function(d){L.Logger.info("Stream subscribed");b.stream=d.stream;d=Erizo.StreamEvent({type:"stream-subscribed",stream:b});a.dispatchEvent(d)},b.pc.oniceconnectionstatechange=function(d){"failed"===d&&0!==a.state&&b&&!b.failed&&(b.failed=!0,L.Logger.warning("Subscribing stream",b.getID(),"has failed after successful ICE checks"),d=Erizo.StreamEvent({type:"stream-failed",
msg:"Subscribing stream failed after connection",stream:b}),a.dispatchEvent(d),a.unsubscribe(b))},b.pc.createOffer(!0),e&&e(!0))}));else if(b.hasData()&&!1!==d.data)g("subscribe",{streamId:b.getID(),data:d.data},void 0,function(d,f){if(null===d)L.Logger.error("Error subscribing to stream ",f),e&&e(void 0,f);else{L.Logger.info("Stream subscribed");var g=Erizo.StreamEvent({type:"stream-subscribed",stream:b});a.dispatchEvent(g);e&&e(!0)}});else{L.Logger.warning("There's nothing to subscribe to");e&&
e(void 0,"Nothing to subscribe to");return}L.Logger.info("Subscribing to: "+b.getID())}else{var h="Error on subscribe";b?b.local&&(L.Logger.warning("Cannot subscribe to local stream, you should subscribe to the remote version of your local stream"),h="Local copy of stream"):(L.Logger.warning("Cannot subscribe to invalid stream",b),h="Invalid or undefined stream");e&&e(void 0,h)}};a.unsubscribe=function(b,d){void 0!==a.socket&&b&&!b.local&&e("unsubscribe",b.getID(),function(a,e){null===a?d&&d(void 0,
e):(j(b),d&&d(!0))},function(){L.Logger.error("Error calling unsubscribe.")})};a.getStreamsByAttribute=function(b,d){var e=[],g,h;for(g in a.remoteStreams)a.remoteStreams.hasOwnProperty(g)&&(h=a.remoteStreams[g],void 0!==h.getAttributes()&&void 0!==h.getAttributes()[b]&&h.getAttributes()[b]===d&&e.push(h));return e};return a};var L=L||{};
L.Logger=function(b){return{DEBUG:0,TRACE:1,INFO:2,WARNING:3,ERROR:4,NONE:5,enableLogPanel:function(){b.Logger.panel=document.createElement("textarea");b.Logger.panel.setAttribute("id","licode-logs");b.Logger.panel.setAttribute("style","width: 100%; height: 100%; display: none");b.Logger.panel.setAttribute("rows",20);b.Logger.panel.setAttribute("cols",20);b.Logger.panel.setAttribute("readOnly",!0);document.body.appendChild(b.Logger.panel)},setLogLevel:function(a){a>b.Logger.NONE?a=b.Logger.NONE:a<
b.Logger.DEBUG&&(a=b.Logger.DEBUG);b.Logger.logLevel=a},log:function(a){var d="";if(!(a<b.Logger.logLevel)){a===b.Logger.DEBUG?d+="DEBUG":a===b.Logger.TRACE?d+="TRACE":a===b.Logger.INFO?d+="INFO":a===b.Logger.WARNING?d+="WARNING":a===b.Logger.ERROR&&(d+="ERROR");for(var d=d+": ",e=[],g=0;g<arguments.length;g++)e[g]=arguments[g];e=e.slice(1);e=[d].concat(e);if(void 0!==b.Logger.panel){d="";for(g=0;g<e.length;g++)d+=e[g];b.Logger.panel.value=b.Logger.panel.value+"\n"+d}else console.log.apply(console,
e)}},debug:function(){for(var a=[],d=0;d<arguments.length;d++)a[d]=arguments[d];b.Logger.log.apply(b.Logger,[b.Logger.DEBUG].concat(a))},trace:function(){for(var a=[],d=0;d<arguments.length;d++)a[d]=arguments[d];b.Logger.log.apply(b.Logger,[b.Logger.TRACE].concat(a))},info:function(){for(var a=[],d=0;d<arguments.length;d++)a[d]=arguments[d];b.Logger.log.apply(b.Logger,[b.Logger.INFO].concat(a))},warning:function(){for(var a=[],d=0;d<arguments.length;d++)a[d]=arguments[d];b.Logger.log.apply(b.Logger,
[b.Logger.WARNING].concat(a))},error:function(){for(var a=[],d=0;d<arguments.length;d++)a[d]=arguments[d];b.Logger.log.apply(b.Logger,[b.Logger.ERROR].concat(a))}}}(L);L=L||{};
L.Base64=function(){var b,a,d,e,g,h,i,j,c;b="A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9,+,/".split(",");a=[];for(g=0;g<b.length;g+=1)a[b[g]]=g;h=function(a){d=a;e=0};i=function(){var a;if(!d||e>=d.length)return-1;a=d.charCodeAt(e)&255;e+=1;return a};j=function(){if(!d)return-1;for(;;){if(e>=d.length)return-1;var b=d.charAt(e);e+=1;if(a[b])return a[b];if("A"===b)return 0}};c=function(a){a=a.toString(16);1===a.length&&(a=
"0"+a);return unescape("%"+a)};return{encodeBase64:function(a){var c,d,e;h(a);a="";c=Array(3);d=0;for(e=!1;!e&&-1!==(c[0]=i());)if(c[1]=i(),c[2]=i(),a+=b[c[0]>>2],-1!==c[1]?(a+=b[c[0]<<4&48|c[1]>>4],-1!==c[2]?(a+=b[c[1]<<2&60|c[2]>>6],a+=b[c[2]&63]):(a+=b[c[1]<<2&60],a+="=",e=!0)):(a+=b[c[0]<<4&48],a+="=",a+="=",e=!0),d+=4,76<=d)a+="\n",d=0;return a},decodeBase64:function(a){var b,d;h(a);a="";b=Array(4);for(d=!1;!d&&-1!==(b[0]=j())&&-1!==(b[1]=j());)b[2]=j(),b[3]=j(),a+=c(b[0]<<2&255|b[1]>>4),-1!==
b[2]?(a+=c(b[1]<<4&255|b[2]>>2),-1!==b[3]?a+=c(b[2]<<6&255|b[3]):d=!0):d=!0;return a}}}(L);Erizo=Erizo||{};Erizo.View=function(){var b=Erizo.EventDispatcher({});b.url="";return b};Erizo=Erizo||{};
Erizo.VideoPlayer=function(b){var a=Erizo.View({});a.id=b.id;a.stream=b.stream.stream;a.elementID=b.elementID;a.destroy=function(){a.video.pause();delete a.resizer;a.parentNode.removeChild(a.div)};a.resize=function(){var d=a.container.offsetWidth,e=a.container.offsetHeight;if(b.stream.screen||!1===b.options.crop)0.5625*d<e?(a.video.style.width=d+"px",a.video.style.height=0.5625*d+"px",a.video.style.top=-(0.5625*d/2-e/2)+"px",a.video.style.left="0px"):(a.video.style.height=e+"px",a.video.style.width=16/
9*e+"px",a.video.style.left=-(16/9*e/2-d/2)+"px",a.video.style.top="0px");else if(d!==a.containerWidth||e!==a.containerHeight)0.75*d>e?(a.video.style.width=d+"px",a.video.style.height=0.75*d+"px",a.video.style.top=-(0.75*d/2-e/2)+"px",a.video.style.left="0px"):(a.video.style.height=e+"px",a.video.style.width=4/3*e+"px",a.video.style.left=-(4/3*e/2-d/2)+"px",a.video.style.top="0px");a.containerWidth=d;a.containerHeight=e};L.Logger.debug("Creating URL from stream "+a.stream);a.stream_url=(window.URL||
webkitURL).createObjectURL(a.stream);a.div=document.createElement("div");a.div.setAttribute("id","player_"+a.id);a.div.setAttribute("class","player");a.div.setAttribute("style","width: 100%; height: 100%; position: relative; background-color: black; overflow: hidden;");a.loader=document.createElement("img");a.loader.setAttribute("style","width: 16px; height: 16px; position: absolute; top: 50%; left: 50%; margin-top: -8px; margin-left: -8px");a.loader.setAttribute("id","back_"+a.id);a.loader.setAttribute("class",
"loader");a.loader.setAttribute("src",a.url+"/assets/loader.gif");a.video=document.createElement("video");a.video.setAttribute("id","stream"+a.id);a.video.setAttribute("class","stream");a.video.setAttribute("style","width: 100%; height: 100%; position: absolute");a.video.setAttribute("autoplay","autoplay");b.stream.local&&(a.video.volume=0);void 0!==a.elementID?(document.getElementById(a.elementID).appendChild(a.div),a.container=document.getElementById(a.elementID)):(document.body.appendChild(a.div),
a.container=document.body);a.parentNode=a.div.parentNode;a.div.appendChild(a.loader);a.div.appendChild(a.video);a.containerWidth=0;a.containerHeight=0;a.resizer=new L.ResizeSensor(a.container,a.resize);a.resize();a.bar=new Erizo.Bar({elementID:"player_"+a.id,id:a.id,stream:b.stream,media:a.video,options:b.options});a.div.onmouseover=function(){a.bar.display()};a.div.onmouseout=function(){a.bar.hide()};a.video.src=a.stream_url;return a};Erizo=Erizo||{};
Erizo.AudioPlayer=function(b){var a=Erizo.View({}),d,e;a.id=b.id;a.stream=b.stream.stream;a.elementID=b.elementID;L.Logger.debug("Creating URL from stream "+a.stream);a.stream_url=(window.URL||webkitURL).createObjectURL(a.stream);a.audio=document.createElement("audio");a.audio.setAttribute("id","stream"+a.id);a.audio.setAttribute("class","stream");a.audio.setAttribute("style","width: 100%; height: 100%; position: absolute");a.audio.setAttribute("autoplay","autoplay");b.stream.local&&(a.audio.volume=
0);b.stream.local&&(a.audio.volume=0);void 0!==a.elementID?(a.destroy=function(){a.audio.pause();a.parentNode.removeChild(a.div)},d=function(){a.bar.display()},e=function(){a.bar.hide()},a.div=document.createElement("div"),a.div.setAttribute("id","player_"+a.id),a.div.setAttribute("class","player"),a.div.setAttribute("style","width: 100%; height: 100%; position: relative; overflow: hidden;"),document.getElementById(a.elementID).appendChild(a.div),a.container=document.getElementById(a.elementID),a.parentNode=
a.div.parentNode,a.div.appendChild(a.audio),a.bar=new Erizo.Bar({elementID:"player_"+a.id,id:a.id,stream:b.stream,media:a.audio,options:b.options}),a.div.onmouseover=d,a.div.onmouseout=e):(a.destroy=function(){a.audio.pause();a.parentNode.removeChild(a.audio)},document.body.appendChild(a.audio),a.parentNode=document.body);a.audio.src=a.stream_url;return a};Erizo=Erizo||{};
Erizo.Bar=function(b){var a=Erizo.View({}),d,e;a.elementID=b.elementID;a.id=b.id;a.div=document.createElement("div");a.div.setAttribute("id","bar_"+a.id);a.div.setAttribute("class","bar");a.bar=document.createElement("div");a.bar.setAttribute("style","width: 100%; height: 15%; max-height: 30px; position: absolute; bottom: 0; right: 0; background-color: rgba(255,255,255,0.62)");a.bar.setAttribute("id","subbar_"+a.id);a.bar.setAttribute("class","subbar");a.link=document.createElement("a");a.link.setAttribute("href",
"http://www.lynckia.com/");a.link.setAttribute("class","link");a.link.setAttribute("target","_blank");a.logo=document.createElement("img");a.logo.setAttribute("style","width: 100%; height: 100%; max-width: 30px; position: absolute; top: 0; left: 2px;");a.logo.setAttribute("class","logo");a.logo.setAttribute("alt","Lynckia");a.logo.setAttribute("src",a.url+"/assets/star.svg");e=function(b){"block"!==b?b="none":clearTimeout(d);a.div.setAttribute("style","width: 100%; height: 100%; position: relative; bottom: 0; right: 0; display:"+
b)};a.display=function(){e("block")};a.hide=function(){d=setTimeout(e,1E3)};document.getElementById(a.elementID).appendChild(a.div);a.div.appendChild(a.bar);a.bar.appendChild(a.link);a.link.appendChild(a.logo);if(!b.stream.screen&&(void 0===b.options||void 0===b.options.speaker||!0===b.options.speaker))a.speaker=new Erizo.Speaker({elementID:"subbar_"+a.id,id:a.id,stream:b.stream,media:b.media});a.display();a.hide();return a};Erizo=Erizo||{};
Erizo.Speaker=function(b){var a=Erizo.View({}),d,e,g,h=50;a.elementID=b.elementID;a.media=b.media;a.id=b.id;a.stream=b.stream;a.div=document.createElement("div");a.div.setAttribute("style","width: 40%; height: 100%; max-width: 32px; position: absolute; right: 0;z-index:0;");a.icon=document.createElement("img");a.icon.setAttribute("id","volume_"+a.id);a.icon.setAttribute("src",a.url+"/assets/sound48.png");a.icon.setAttribute("style","width: 80%; height: 100%; position: absolute;");a.div.appendChild(a.icon);
a.stream.local?(e=function(){a.media.muted=!0;a.icon.setAttribute("src",a.url+"/assets/mute48.png");a.stream.stream.getAudioTracks()[0].enabled=!1},g=function(){a.media.muted=!1;a.icon.setAttribute("src",a.url+"/assets/sound48.png");a.stream.stream.getAudioTracks()[0].enabled=!0},a.icon.onclick=function(){a.media.muted?g():e()}):(a.picker=document.createElement("input"),a.picker.setAttribute("id","picker_"+a.id),a.picker.type="range",a.picker.min=0,a.picker.max=100,a.picker.step=10,a.picker.value=
h,a.picker.setAttribute("orient","vertical"),a.div.appendChild(a.picker),a.media.volume=a.picker.value/100,a.media.muted=!1,a.picker.oninput=function(){0<a.picker.value?(a.media.muted=!1,a.icon.setAttribute("src",a.url+"/assets/sound48.png")):(a.media.muted=!0,a.icon.setAttribute("src",a.url+"/assets/mute48.png"));a.media.volume=a.picker.value/100},d=function(b){a.picker.setAttribute("style","background: transparent; width: 32px; height: 100px; position: absolute; bottom: 90%; z-index: 1;"+a.div.offsetHeight+
"px; right: 0px; -webkit-appearance: slider-vertical; display: "+b)},e=function(){a.icon.setAttribute("src",a.url+"/assets/mute48.png");h=a.picker.value;a.picker.value=0;a.media.volume=0;a.media.muted=!0},g=function(){a.icon.setAttribute("src",a.url+"/assets/sound48.png");a.picker.value=h;a.media.volume=a.picker.value/100;a.media.muted=!1},a.icon.onclick=function(){a.media.muted?g():e()},a.div.onmouseover=function(){d("block")},a.div.onmouseout=function(){d("none")},d("none"));document.getElementById(a.elementID).appendChild(a.div);
return a};
module.exports = Erizo;
